---

- name: Ensure backups directory exists
  file: path="{{ item }}" state=directory mode=0700
  with_items:
    - "{{ backups_dir }}"
    - "{{ backups_dir }}/mysql"
    - "{{ backups_dir }}/postgres"
    - "{{ backups_dir }}/shop"
    - "{{ backups_dir }}/forum"
