---

- name: Disable the default nginx vhost
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  remote_user: root
  notify:
    - reload nginx

- name: Ensure the log directory exists
  file:
    path: /var/log/nginx/{{ nginx_prefix }}
    state: directory
    owner: www-data
    group: www-data
  remote_user: root

- name: Ensure the docroot exists
  file:
    path: "{{ docroot }}"
    state: directory
  when: nginx_vhost_template == 'vhost.j2'

- name: Install the Nginx config file
  template:
    src: "{{ nginx_vhost_template }}"
    dest: "/etc/nginx/sites-available/{{ nginx_prefix }}.conf"
  remote_user: root
  notify:
    - reload nginx

- name: Ensure the site is enabled (symlink)
  file:
    src: "/etc/nginx/sites-available/{{ nginx_prefix }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ nginx_prefix }}.conf"
    state: link
  remote_user: root
  notify:
    - reload nginx
