---

mb_docker_host: '172.17.0.1'

mb_docker_network: mb_docker

mb_docker_volume_prefix: mb_docker
mb_docker_volume_storage_root: /mnt/bigstorage

mb_docker_version: latest

mb_docker_nginx_user: www-data
mb_docker_apache_user: "{{ mb_docker_nginx_user }}"
mb_docker_django_user: modelbrouw
mb_docker_django_group: "{{ mb_docker_django_user }}"

mb_docker_volumes:
  static:
    name: "{{ mb_docker_volume_prefix }}-static"
    perms: o=rwx,g=rx,o=rx
    owner: "{{ mb_docker_django_user }}"
    group: "{{ mb_docker_django_group }}"
    symlink: "{{ mb_docker_volume_storage_root }}/static"

  media:
    name: "{{ mb_docker_volume_prefix }}-media"
    perms: o=rwx,g=rx,o=
    owner: "{{ mb_docker_django_user }}"
    group: "{{ mb_docker_django_group }}"
    symlink: "{{ mb_docker_volume_storage_root }}/media"

  media_sendfile:
    name: "{{ mb_docker_volume_prefix }}-media_sendfile"
    perms: o=rwx,g=rx,o=
    owner: "{{ mb_docker_django_user }}"
    group: "{{ mb_docker_django_group }}"
    symlink: "{{ mb_docker_volume_storage_root }}/media_sendfile"

  logs:
    name: "{{ mb_docker_volume_prefix }}-logs"
    perms: o=rw,g=r,o=
    owner: "{{ mb_docker_django_user }}"
    group: root

  phpbb_cache:
    name: "{{ mb_docker_volume_prefix }}-phpbb_cache"
    perms: o=rw,g=r,o=
    owner: "{{ mb_docker_apache_user }}"
    group: "{{ mb_docker_apache_user }}"

  phpbb_images:
    name: "{{ mb_docker_volume_prefix }}-phpbb_images"
    perms: o=rw,g=rx,o=
    owner: "{{ mb_docker_apache_user }}"
    group: "{{ mb_docker_django_group }}"
    symlink: "{{ mb_docker_volume_storage_root }}/phpbb_images"

  shop:
    name: "{{ mb_docker_volume_prefix }}-shop"
    perms: o=rw,g=rx,o=
    owner: "{{ mb_docker_apache_user }}"
    group: "{{ mb_docker_django_group }}"
    symlink: "{{ mb_docker_volume_storage_root }}/shop"

# container options
mb_docker_hostname_suffix: ''

mb_docker_default_from_email: 'webmaster@localhost'
mb_docker_email_contact_notification: 'webmaster@localhost'

mb_docker_memcached_image: index.docker.io/library/memcached:1.6
mb_docker_redis_image: index.docker.io/library/redis:6

mb_docker_django_image: "index.docker.io/modelbrouwers/brouwers:{{ mb_docker_version }}"
mb_docker_django_domain: django.modelbrouwers.nl
mb_docker_django_allowed_hosts:
  - "{{ mb_docker_django_domain }}"
  - localhost
mb_docker_django_session_cookie_domain: "{{ mb_docker_django_domain }}"
mb_docker_django_secret_key: ''
mb_docker_django_db:
  postgres:
    name: postgres
    user: postgres
    password: ''
  mysql:
    name: mysql
    user: root
    password: ''
  legacy_shop:
    name: mysql
    user: root
    password: ''
mb_docker_django_port: 8000
mb_docker_django_mibbit_settings: ''
mb_docker_django_sentry_dsn: ''

mb_docker_phpbb_image: "index.docker.io/modelbrouwers/phpbb:{{ mb_docker_version }}"
mb_docker_phpbb_uid_cookie: 'phpbb3_u'
mb_docker_phpbb_port: 8001
mb_docker_phpbb_db:
  mysql:
    name: mysql
    user: root
    password: ''
  postgres:
    name: postgres
    user: postgres
    password: ''
mb_docker_phpbb_sentry_dsn: ''

mb_docker_shop_image: "docker.modelbrouwers.nl/modelbrouwers/winkel:{{ mb_docker_version }}"
mb_docker_shop_db:
  name: mysql
  user: root
  password: ''
mb_docker_shop_port: 8002
mb_docker_shop_self_address: https://shop.modelbrouwers.nl
mb_docker_shop_redis_url: "redis-{{ mb_docker_hostname_suffix | mandatory }}:6379?database=2"

mb_docker_registry:
  registry_url: docker.modelbrouwers.nl
  username: ''
  password: ''

mb_docker_server:
  name: "{{ mb_docker_django_domain }}"
  aliases: []

mb_docker_cronjobs: []

mb_docker_geoip_database_path: /tmp/geoip/
