---

- name: Ensure download folder exists
  file: dest={{ ansible_env.HOME }}/downloads/ state=directory

- name: Download the opencart installer
  unarchive:
    src="{{ opencart_url }}"
    dest={{ ansible_env.HOME }}/downloads/
    copy=no
    creates={{ ansible_env.HOME }}/downloads/{{ opencart_dir }}

- name: Ensure public_html folder exists
  file: dest={{ ansible_env.HOME }}/public_html/ state=directory

- name: stat 'winkel' folder
  stat: path={{ ansible_env.HOME }}/public_html/winkel/
  register: stat_winkel

- name: Move shop to public_html
  command: mv {{ ansible_env.HOME }}/downloads/{{ opencart_dir }}/upload {{ ansible_env.HOME }}/public_html/winkel
  when: not stat_winkel.stat.exists

- name: Create database user for the shop
  mysql_user:
    name="{{ shop_db.user }}"
    password="{{ shop_db.password }}"
    host=localhost
    state=present
  remote_user: root

- name: Create database for the shop
  mysql_db: name="{{ shop_db.name }}" state=present
  remote_user: root

- name: Grant db user privileges
  mysql_user: name="{{ shop_db.user }}" priv="{{ shop_db.name }}.*:ALL"
  remote_user: root
