---

- name: Clone extensions repository
  git:
    repo: "{{ opencart_extensions_repo }}"
    dest: "{{ ansible_env.HOME }}/opencart-extensions"
    version: "{{ shop_extensions_version }}"
    accept_hostkey: yes
  register: extensions_clone

- name: Run the extensions installer
  command: bash install_all.sh {{ shop_path }}
  args:
    chdir: "{{ ansible_env.HOME }}/opencart-extensions"
  when: extensions_clone.changed

- name: Set group-write permissions on the base directories (TicketFactory)
  file:
    path: "{{ shop_path }}/{{ item }}"
    state: directory
    mode: 0770
  with_items:
    - achterdeur
    - catalog

- name: Symlink site-wide header
  file:
    src: "{{ django_root }}/src/templates/php_templates/top.php"
    dest: "{{ shop_path }}/catalog/view/theme/default/template/common/top.php"
    state: link
