---
- name: Ensure the log directory exists
  file: dest=/var/log/apache2/{{ user }} state=directory owner=www-data group=www-data
  remote_user: root

- name: Install the Apache config file
  template:
    src=httpd.conf.j2
    dest=/etc/apache2/sites-available/{{ user }}.conf
  remote_user: root
  notify:
    - reload apache

- name: Ensure that the needed modules are enabled
  file:
    src=../mods-available/{{ item }}
    dest=/etc/apache2/mods-enabled/{{ item }}
    state=link
  with_items:
    - headers.load
    - php5.load
    - php5.conf
  remote_user: root
  notify:
    - reload apache

- name: Ensure the site is enabled (symlink)
  file:
    src=../sites-available/{{ user }}.conf
    dest=/etc/apache2/sites-enabled/{{ user }}.conf
    state=link
  remote_user: root
  notify:
    - reload apache
