---

- name: Deploy the Modelbrouwers.nl domain
  hosts: new
  remote_user: modelbrouw
  vars:
    user: modelbrouw
    opencart_url: "https://www.opencart.com/index.php?route=download/download/download&download_id=31"
    opencart_dir: opencart-1.5.5.1
    vqmod_url: "https://github.com/vqmod/vqmod/releases/download/v2.6.1-opencart/vqmod-2.6.1-opencart.zip"
    vqmod_dir: vqmod
    opencart_extensions_repo: "ssh://git@bitbucket.org/modelbrouwers/opencart-extensions.git"
    server:
      name: modelbrouwers.nl
      aliases:
        - new.modelbrouwers.nl
        # - www.modelbrouwers.nl
        # - shop.modelbrouwers.nl
    uwsgi:
      port: 8002
    home_ip: 163.158.222.105
  roles:
    # - apache
    # - nginx
    - shop
