---

- name: Deploy the Modelbrouwers.nl domain
  hosts: web
  remote_user: modelbrouw
  roles:
    - role: apache
      tags:
        - apache
    - nginx
    - maintenance_on
    - django  # fixme: requires mysql db (user) to exist to run migrations
    - role: forum
      tags:
        - forum
    - supervisor
    - maintenance_off
  become_method: su
