---

- name: Deploy the Modelbrouwers.nl domain
  hosts: web
  remote_user: modelbrouw
  roles:
    - role: apache
      tags:
        - apache
    - nginx
    - shop
    - maintenance_on
    - django
    - forum
    - supervisor
    - maintenance_off
  become_method: su
