---

- name: Deploy the Modelbrouwers.nl domain
  hosts: new
  remote_user: modelbrouw
  roles:
    - apache
    - nginx
    - shop
    - maintenance_on
    - django
    - forum
    - supervisor
    - maintenance_off
  become_method: su
