---

- name: Deploy the web-applications (as containers)
  hosts: web
  remote_user: root

  vars_files:
    - vars/certbot.yml

  vars:
    docroot: "/home/modelbrouw/public_html{{ '/staging' if env == 'staging' else '' }}"

    mb_docker_network: "modelbrouwers-{{ env }}"
    mb_docker_volume_prefix: "mb-{{ env }}"
    mb_docker_volume_storage_root: "/mnt/bigstorage/modelbrouw/{{ env }}"
    mb_docker_geoip_database_path: "/mnt/bigstorage/modelbrouw/GeoIP/"

    mb_docker_hostname_suffix: "mb-{{ env }}"
    mb_docker_default_from_email: "{{ django.from_email }}"
    mb_docker_email_contact_notification: "{{ django.contact_email }}"

    mb_docker_django_domain: "{{ server.name }}"
    mb_docker_django_secret_key: "{{ django.secret_key }}"
    mb_docker_django_db:
      postgres: "{{ django_db }}"
      mysql: "{{ forum_db }}"
      legacy_shop: "{{ shop_db }}"
    mb_docker_django_port: "{{ uwsgi.port }}"
    mb_docker_django_mibbit_settings: "{{ mibbit_settings }}"
    mb_docker_django_sentry_dsn: "{{ sentry.django }}"

    mb_docker_phpbb_uid_cookie: phpbb3_10uny8_u
    mb_docker_phpbb_db:
      mysql: "{{ forum_db }}"
      postgres: "{{ django_db }}"
    mb_docker_phpbb_port: "{{ phpbb.port }}"
    mb_docker_phpbb_sentry_dsn: "{{ sentry.php }}"

    mb_docker_shop_db: "{{ shop_db }}"
    mb_docker_shop_port: "{{ shop.port }}"
    mb_docker_shop_self_address: "https://{{ inventory_hostname }}"

    mb_docker_server:
      name: "{{ server.name }}"
      aliases: "{{ server.aliases }}"

    certbot_certs:
      - domains: "{{ [mb_docker_server.name] + mb_docker_server.aliases }}"
      - domains:
        - "albums.{{ mb_docker_server.name }}"

  roles:
    # - role: geerlingguy.docker
    - role: mb_docker
      tags:
        - apps
    - role: geerlingguy.certbot
      tags:
        - nginx
    - role: nginx
      vars:
        nginx_install_ssl: false  # certbot
        nginx_prefix: "{{ mb_docker_nginx_prefix }}"
        nginx_vhost_template: "{{ mb_docker_nginx_template }}"
      tags:
        - nginx
