---

- name: Deploy the web-applications (as containers)
  hosts: web
  remote_user: root

  vars:
    mb_docker_network: "modelbrouwers-{{ env }}"
    mb_docker_volume_prefix: "mb-{{ env }}"
    mb_docker_volume_storage_root: "/mnt/bigstorage/modelbrouw/{{ env }}"

    mb_docker_hostname_suffix: "mb-{{ env }}"
    mb_docker_default_from_email: "{{ django.from_email }}"

    mb_docker_django_domain: "{{ server.name }}"
    mb_docker_django_secret_key: "{{ django.secret_key }}"
    mb_docker_django_db:
      postgres: "{{ django_db }}"
      mysql: "{{ forum_db }}"
    mb_docker_django_port: "{{ uwsgi.port }}"
    mb_docker_django_mibbit_settings: "{{ mibbit_settings }}"
    mb_docker_django_sentry_dsn: "{{ sentry.django }}"

    mb_docker_phpbb_uid_cookie: phpbb3_10uny8_u
    mb_docker_phpbb_db:
      mysql: "{{ forum_db }}"
      postgres: "{{ django_db }}"
    mb_docker_phpbb_port: "{{ phpbb.port }}"
    mb_docker_phpbb_sentry_dsn: "{{ sentry.php }}"

  roles:
    - role: geerlingguy.docker
    - role: mb_docker
      tags:
        - apps
