---
# Deploys the application code to the server
- name: update the application to the latest version
  hosts: web
  vars:
    deploy_env: staging
    repository: https://github.com/modelbrouwers/modelbrouwers.git
    release: master
    settings_module: conf.settings.staging
  remote_user: modelbrouw
  roles:
    - django
