---
# Deploys the application code to the server
- name: Update the application to the latest version
  hosts: web
  vars:
    deploy_env: "{{ target|default('staging') }}"
    release: "{{ release_tag|default('master') }}"
    repository: https://github.com/modelbrouwers/modelbrouwers.git
    settings_module: conf.settings.{{ deploy_env }}
    project_home: "{{ ansible_env.HOME }}/django/{{ deploy_env }}"
    docroot_map: {staging: "{{ ansible_env.HOME }}/public_html/staging", production: "{{ ansible_env.HOME }}/public_html"}
    docroot: "{{ docroot_map.get(deploy_env) }}"
  remote_user: modelbrouw
  roles:
    - maintenance_on
    - nginx
    - django
    - php
    - shop
    - maintenance_off
