---

# Checklist:
# - [x] Hostname properly configured (no IP adresses)
# - [x] DNS configured (MX, A and PTR)
# - [ ] SSL cert set up for dynamic domains
# - [x] Encryption set up
# - [x] Virtual domains & forwards migrated
# - [x] Mailboxes correctly migrated & functional
# - [x] Ensure docker container IP adresses are still in mynetworks
#     - 172.17.0.2
#     - 172.17.0.3
#     - 172.17.0.4
# - [x] inet_interfaces = localhost, 172.17.0.1
# - [ ] webmail
# - [ ] Maildir default dirs

- name: Set up the mailserver for outgoing and incoming e-mail
  hosts: mail
  remote_user: root

  vars_files:
    - vars/certbot.yml

  vars:
    postfixer_postgresql_version: '9.6'

  roles:
    - role: geerlingguy.docker
    - role: geerlingguy.certbot
    - role: postfixer
    - role: nginx
      tags:
        - nginx
    - role: postfix
      tags:
        - postfix
    - role: dovecot
      tags:
        - postfix
