---

# Checklist:
# - [x] Hostname properly configured (no IP adresses)
# - [x] DNS configured (MX, A and PTR)
# - [ ] SSL cert set up for dynamic domains
# - [x] Encryption set up
# - [x] Virtual domains & forwards migrated
# - [x] Mailboxes correctly migrated & functional
# - [x] Ensure docker container IP adresses are still in mynetworks
#     - 172.17.0.2
#     - 172.17.0.3
#     - 172.17.0.4
# - [x] inet_interfaces = localhost, 172.17.0.1
# - [ ] webmail
# - [ ] Maildir default dirs

- name: Set up the mailserver for outgoing and incoming e-mail
  hosts: mail
  remote_user: root

  vars:
    postfixer_postgresql_version: '9.6'

    certbot_create_standalone_stop_services:
      - nginx
    certbot_auto_renew_options: >
      --nginx --quiet --no-self-upgrade
      --post-hook 'service nginx reload && service postfix reload && service dovecot reload'

  roles:
    - role: geerlingguy.docker
    - role: geerlingguy.certbot
    - role: postfixer
    - role: nginx
      tags:
        - nginx
    - role: postfix
      tags:
        - postfix
    - role: dovecot
      tags:
        - postfix
