---

# Checklist:
# - [x] Hostname properly configured (no IP adresses)
# - [x] DNS configured (MX, A and PTR)
# - [ ] SSL cert set up for dynamic domains
# - [x] Encryption set up
# - [x] Virtual domains & forwards migrated
# - [x] Mailboxes correctly migrated & functional
# - [x] Ensure docker container IP adresses are still in mynetworks
#     - 172.17.0.1/11
# - [x] inet_interfaces = localhost, 172.17.0.1
# - [x] webmail
# - [ ] Maildir default dirs

- name: Set up the mailserver for outgoing and incoming e-mail
  hosts: mail
  remote_user: root

  vars_files:
    - vars/certbot.yml

  vars:
    postfixer_postgresql_version: '11'
    roundcube_postgresql_version: '11'

  roles:
    - role: geerlingguy.docker
    - role: geerlingguy.certbot
    - role: postfixer
    - role: nginx
      vars:
        nginx_install_ssl: false
        nginx_vhost_template: proxy.j2
        nginx_hostname: "{{ postfixer_hostname }}"
        nginx_proxy_port: "{{ postfixer_port }}"
    - role: postfix
    - role: dovecot
    - role: roundcube
    - role: nginx
      vars:
        nginx_prefix: roundcube
        nginx_install_ssl: false
        nginx_vhost_template: proxy.j2
        nginx_hostname: "{{ _roundcube_domains|join(' ') }}"
        nginx_ssl_host: "{{ _roundcube_domains[0] }}"
        nginx_proxy_port: "{{ _roundcube_container_port }}"
