---

# - name: Create database backups
#   hosts: web
#   remote_user: root
#   tasks:
#     - name: Backup postgres database
#       command: pg_dump -F c -f /tmp/modelbrouwers.custom modelbrouwers
#       become: yes
#       become_user: postgres

#     - name: Backup MySQL databases
#       mysql_db:
#         state=dump name={{ item }} target=/tmp/{{ item }}.sql
#         login_user={{ mysql_user }} login_password={{ mysql_password }}
#       with_items:
#         - modelbrouw_fora
#         - modelbrouw_winkl



- name: Transfer the (old) production data to the new server
  hosts: new
  remote_user: modelbrouw
  tasks:
    # - name: Transfer the backup files
    #   synchronize: src=/tmp/{{ item }} dest=/tmp/{{ item }}
    #   delegate_to: modelbrouwers.nl
    #   with_items:
    #     - modelbrouwers.custom
    #     - modelbrouw_fora.sql
    #     - modelbrouw_winkl.sql

    - name: Copy the uploaded files from old to new
      synchronize: src=/home/modelbrouw/{{ item }}/ dest=/home/modelbrouw/{{ item }}
      delegate_to: modelbrouwers.nl
      with_items:
        - public_html/phpBB3/images
        - public_html/winkel/image

    - name: Sync media folder
      synchronize: src=/home/modelbrouw/django/production/media/ dest=/home/modelbrouw/django/production/media
      delegate_to: modelbrouwers.nl
