---

# Playbook to set up a new server from scratch

- name: Provision the server
  hosts: new
  remote_user: root
  vars:
    admin_email: "sergei@modelbrouwers.nl"
  roles:
    - base
    # - ftp
    - mail
    - users
    - newrelic
