---

- name: Symlink auth plugin
  file:
    src: "{{ django_src }}/src/phpbb/phpBB3/includes/auth/{{ item }}"
    dest: "{{ forum_path }}/includes/auth/{{ item }}"
    state: link
  with_items:
    - getdjangouser.php
    - auth_django.php

- name: Symlink docroot
  file:
    src: "{{ docroot }}"
    dest: "{{ django_src }}/public_html"
    state: link
    force: yes

- name: Ensure paths exist
  file:
    path: "{{ forum_path }}/{{ item }}"
    state: directory
  with_items:
    - src
    - src/conf

- name: Symlink code root (Docker setup compatibility)
  file:
    src: "{{ django_src }}/src/{{ item }}"
    dest: "{{ forum_path }}/src/{{ item }}"
    state: link
  with_items:
    - conf/settings.php
    - phpbb
    - templates

- name: Disable re-auth for phpBB admin
  lineinfile:
    dest="{{ forum_path }}/adm/index.php"
    regexp="login_box\('', \$user->lang\['LOGIN_ADMIN_CONFIRM'\], \$user->lang\['LOGIN_ADMIN_SUCCESS'\], true, false\);"
    line="//    login_box('', $user->lang['LOGIN_ADMIN_CONFIRM'], $user->lang['LOGIN_ADMIN_SUCCESS'], true, false);"

- name: Ensure X-Forwarded-For header is respected
  blockinfile:
    dest: "{{ forum_path }}/includes/startup.php"
    block: |
      // Fix for reverse proxy
      if(!empty($_SERVER['HTTP_X_FORWARDED_FOR']) && $_SERVER['SERVER_ADDR'] == $_SERVER['REMOTE_ADDR']) {
              $_SERVER['REMOTE_ADDR'] = htmlspecialchars((string) $_SERVER['HTTP_X_FORWARDED_FOR']);
      }
    insertbefore: "// Report all errors, except notices and deprecation messages"


- name: Set up custom styles
  file:
    src: "{{ django_src }}/src/phpbb/phpBB3/styles/subsilver2_dead_topics"
    dest: "{{ forum_path }}/styles/subsilver2_dead_topics"
    state: link

- name: Install dependencies with composer
  composer:
    working_dir: "{{ django_src }}"

- name: Bundle the SystemJS apps
  shell: php bin/systemjs_bundle.php jspm:bundle
  args:
    chdir: "{{ django_src }}"

- name: Clear the phpBB3 template cache
  shell: rm -rf {{ forum_path }}/phpBB3/cache/*tpl_*.html.php
