---

- name: Ensure phpBB container is running
  community.general.docker_container:
    container_default_behavior: no_defaults
    name: "phpbb-{{ mb_docker_hostname_suffix | mandatory }}"
    state: started
    image: "{{ mb_docker_phpbb_image }}"
    pull: yes
    hostname: "phpbb-{{ mb_docker_hostname_suffix | mandatory }}"
    networks:
      - name: "{{ mb_docker_network }}"
    network_mode: "{{ mb_docker_network }}"
    purge_networks: yes
    networks_cli_compatible: yes
    privileged: no
    restart_policy: always
    memory: 500M
    memory_reservation: 100M
    volumes:
      - "{{ mb_docker_volumes.phpbb_cache.name }}:/var/www/html/phpBB3/cache"
      - "{{ mb_docker_volumes.phpbb_images.name }}:/var/www/html/phpBB3/images"
    env:
      PHPBB3_DB_HOST: "{{ mb_docker_host }}"
      PHPBB3_DB_NAME: "{{ mb_docker_phpbb_db.mysql.name }}"
      PHPBB3_DB_USER: "{{ mb_docker_phpbb_db.mysql.user }}"
      PHPBB3_DB_PASSWORD: "{{ mb_docker_phpbb_db.mysql.password }}"
      PHPBB3_DJANGO_DB_HOST: "{{ mb_docker_host }}"
      PHPBB3_DJANGO_DB_NAME: "{{ mb_docker_phpbb_db.postgres.name }}"
      PHPBB3_DJANGO_DB_USER: "{{ mb_docker_phpbb_db.postgres.user }}"
      PHPBB3_DJANGO_DB_PASSWORD: "{{ mb_docker_phpbb_db.postgres.password }}"
      MEMCACHED_HOST: "memcached-{{ mb_docker_hostname_suffix | mandatory }}"
      RAVEN_DSN: "{{ mb_docker_phpbb_sentry_dsn }}"
    ports:
      - "{{ mb_docker_phpbb_port }}:80"
    comparisons:
      env: strict
      volumes: strict
