---

- name: Ensure media folder exists
  file: path={{ storage_path }} state=directory mode=0750 owner="{{ ansible_ssh_user }}"

- name: Ensure media folder is symlink to big storage
  file:
    src={{ storage_path }}
    dest={{ project_home }}/media
    state=link
