---

mb_docker_nginx_prefix: "{{ mb_docker_hostname_suffix | replace('-', '_') }}"
mb_docker_nginx_log_dir: "/var/log/nginx/{{ mb_docker_nginx_prefix }}"

# Certbot/Let's Encrypt
mb_docker_nginx_certs: "/etc/letsencrypt/live/{{ mb_docker_server.name }}"
