---

- name: Install the databases used
  apt: name={{ item }} state=present force=yes
  with_items:
    - postgresql
    - postgresql-client

    - mysql-server
    - mysql-client

    - python-dev

    - libpq-dev
    - python-psycopg2

    - libmysqlclient-dev
    - python-mysqldb

- name: ensure mysql is running and starts on boot
  service: name=mysql state=started enabled=true

- name: copy .my.cnf file with root password credentials
  template: src=my.cnf dest=/root/.my.cnf owner=root mode=0600


# Set up MYSQL properly

# Need to do this for idempotency, see
# http://ansible.cc/docs/modules.html#mysql-user
- name: update mysql root password for all root accounts
  mysql_user: name=root host=localhost password={{ root_mysql_password }}

- name: update mysql root password for all root accounts
  mysql_user: name=root host_all=yes password={{ root_mysql_password }}

- name: Remove the anonymous users
  mysql_user: name='' host_all=yes state=absent

- name: remove the test database
  mysql_db: name=test state=absent


# Set up PostgreSQL properly

- name: Install correct pg_hba.conf rules for postgres user
  lineinfile: dest=/etc/postgresql/9.4/main/pg_hba.conf
              regexp='^local   all             (all|postgres)                                \s*(peer|ident)'
              line='local   all             postgres                                ident'
  notify:
    - restart postgres

- name: Enforce password auth for local postgres connections
  lineinfile: dest=/etc/postgresql/9.4/main/pg_hba.conf
              insertafter='local   all             postgres                                ident'
              line='local   all             all                                     md5'
  notify:
    - restart postgres
