---

- name: Install the databases used
  apt: name={{ item }} state=present force=yes
  with_items:
    - postgresql
    - postgresql-client

    - mysql-server
    - mysql-client

    - python-dev

    - libpq-dev
    - python-psycopg2

    - libmysqlclient-dev
    - python-mysqldb
