---

- name: Install php
  package: name="{{ item }}" state=present
  with_items:
    - php5
    - php5-mysql
    - php5-pgsql
    - libapache2-mod-php5
    - php5-mcrypt
    - php5-curl
    - php5-gd
