---

- name: Install nginx
  apt: name=nginx state=present

- name: Install libgeoip for nginx module
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - libgeoip-dev
    - libnginx-mod-http-geoip2

- name: Set main config files
  copy:
    src: "nginx/{{ item }}"
    dest: "/etc/nginx/{{ item }}"
  notify:
    - restart nginx
  with_items:
    - nginx.conf
    - conf.d/client_body.conf
    - conf.d/proxy.conf
