---

- name: Install Apache to listen on localhost
  apt: name=apache2 state=present

- name: Disable the default site
  file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
  notify:
    - reload apache

- name: Don't listen on ports 80 and 443
  copy: src=apache/ports.conf dest=/etc/apache2/ports.conf
  notify:
    - reload apache


- name: Install nginx
  apt: name=nginx state=present

- name: Set main config file
  copy: src=nginx/nginx.conf
        dest=/etc/nginx/nginx.conf
  notify:
    - restart nginx
