---
# Install the php dependencies

- name: Install dependencies with composer
  composer: working_dir={{ project_home }}


- name: Bundle the SystemJS apps
  shell: php bin/systemjs_bundle.php jspm:bundle --jspm-executable /opt/bin/jspm
         chdir={{ project_home }}
  environment:
    PATH: /opt/bin/:{{ ansible_env.PATH }}


- name: Clear the phpBB3 template cache
  shell: find . -name '*tpl_*.html.php' -exec rm {} \;
  args:
    chdir: "{{ docroot }}/phpBB3/cache"
